name: pages-build-deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create directory for Python symlink
      run: mkdir -p /github/workspace/packages/core/build/node_gyp_bins

    - name: Create Python symlink
      run: ln -s $(which python3) /github/workspace/packages/core/build/node_gyp_bins/python3

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build project
      run: |
        
