name: CI for H3Tag Blockchain

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & Test H3Tag Blockchain
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.18.1]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache liboqs build
      - name: Cache liboqs
        id: cache-liboqs
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/lib/liboqs*
            /usr/local/include/oqs
            /usr/local/lib/cmake/liboqs
          key: ${{ runner.os }}-liboqs-${{ hashFiles('liboqs/**') }}
          restore-keys: |
            ${{ runner.os }}-liboqs-

      # Install system dependencies including liboqs
      - name: Install system dependencies
        if: steps.cache-liboqs.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build
          git clone --branch main https://github.com/open-quantum-safe/liboqs.git
          cd liboqs
          mkdir build && cd build
          cmake -GNinja -DBUILD_SHARED_LIBS=ON ..
          ninja
          sudo ninja install
          sudo ldconfig

      # Update ldconfig if using cached version
      - name: Update ldconfig for cached liboqs
        if: steps.cache-liboqs.outputs.cache-hit == 'true'
        run: sudo ldconfig

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # Force yarn to use node version from matrix
      - name: Set node version for yarn
        run: |
          yarn config set nodeLinker node-modules
          yarn config set nodePath $(which node)

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      # NX cache
      - name: NX Cache
        uses: actions/cache@v3
        with:
          path: |
            dist
            build
            .nx/cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-nx-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build shared package first
        run: yarn nx build @h3tag-blockchain/shared

      - name: Build crypto package
        run: yarn nx build @h3tag-blockchain/crypto

      - name: Build core package
        run: yarn nx build @h3tag-blockchain/core

      - name: Build api package
        run: yarn nx build @h3tag-blockchain/api

      - name: Build cli package
        run: yarn nx build @h3tag-blockchain/cli

      - name: Lint affected projects
        run: yarn nx affected:lint --parallel=3

      # Run affected tests first
      - name: Run affected tests
        run: yarn nx affected:test --parallel=3 --coverage

      # Then run all tests
      - name: Run all tests
        run: yarn nx run-many --target=test --all --parallel=3 --coverage

      # Upload coverage reports
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            **/coverage
            **/lcov.info
          retention-days: 14
